### ISSUE TITLE
PyPI statistics download

### ISSUE THREAD

**Issue by jeyarajm** [pypa/bandersnatch#1114]
Dear All,

How to download the 11.0 TB of PyPI statistics package's.

Please find the below links

https://pypi.org/stats/

????

Thanks,
Jeyaraj.M

**Comment by cooperlees** [comment]
What do you actually want here? Ever single packages size? I can't remember if `/stats` allows getting all packages sizes due to resources it would take.

`/stats` I think only shows the top 100 packages. It is also an API (I added this to PyPI). So I also wrote a client for the API to generate a Bandersnatch compatible config here: https://github.com/cooperlees/pypistats

Hope that helps. Thanks.
