### ISSUE TITLE
Implement PEP 691 JSON Simple Index Support

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#1138]
Add logic for bandersnatch to save both the HTML and JSON simple index files. This will allow people to serve both the HTML and JSON in their mirrors.
- Happy to introduce a config to select the formats to save
  - Eventually most tools should prefer the JSON we would expect

We should also update docs + give an example way to serve based on request headers (conneg) as outlined in [PEP691](https://peps.python.org/pep-0691/).

**Comment by dstufft** [comment]
One additional thing:

The above assumes that bandersnatch is going to swap out from writing *just* ``index.html`` files, to writing the 3 files mentioned above alongside each other, which makes a lot of sense for people who want a single URL to support all of the content types available.

Some people may want to not rely on conneg, and have different URLs for different content types. I think bandersnatch could support this pretty easily using two options:

1. If a configuration format is introduced to filter the content types that bandersnatch will emit, then obviously you could just run multiple copies of bandersnatch with different content types filtered.
2. Support an option to store the different content types in different root directories, so instead of something like ``/data/pypi/web/simple/pkgname/``, if this option was turned on you would do ``/data/pypi/web/simple/html/pkgname/``, ``/data/pypi/web/simple/v1+json/pkgname/``, etc.
   - Using this would then mean doing something like ``pip install -i https://example.com/simple/v1+json/``.
   - This might be YAGNI, maybe nobody actually wants to do this. Just a random idea that popped into my head that is supported by PEP691, that people *might* want to do.

**Comment by cooperlees** [comment]
#1154 + #1161
