### ISSUE TITLE
PEP484 type annotate all of bandersnatch

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#15]
Lets add PEP484 type annotations to all source code and get clean passing `mypy` checks.

Mypy: http://mypy.readthedocs.io/en/stable/getting_started.html
typing module: https://docs.python.org/3/library/typing.html

**Comment by pradyunsg** [comment]
Useful tools here:

- https://github.com/dropbox/pyannotate/
- https://github.com/Instagram/MonkeyType

**Comment by cooperlees** [comment]
Ok - Only plugins left to strictly type annotate. Help welcome or I'll eventually get to it.

**Comment by cooperlees** [comment]
I didn't mean to close this! lol

**Comment by rkm** [comment]
Hi! I can probably finish this off if you can point me in the right direction

**Comment by cooperlees** [comment]
No problem. What's left is all the test code here:

https://github.com/pypa/bandersnatch/tree/master/src/bandersnatch/tests

## How I'd go about this
- Remove `src/bandersnatch/tests/.*` from https://github.com/pypa/bandersnatch/blob/master/.pre-commit-config.yaml#L33
- Make a virtualenv - install requrements.txt + requirements_dev.txt
- run mypy and make it all pass :D

**Comment by rkm** [comment]
hi, just a quick update. I've made a start on this here: https://github.com/pypa/bandersnatch/compare/master...rkm:issue/15-pep484-type-annotations. Turns out pytest is not very pep484-friendly currently, so I've had to import some of its private members to keep mypy happy. Interested to hear any suggestions!

some related issues:
- pytest typing - https://github.com/pytest-dev/pytest/issues/3342
- false unreachable after `pytest.raises` block - https://github.com/python/mypy/issues/8985

**Comment by cooperlees** [comment]
Awesome stuff! Really appreciate the efforts. I'm also open to accepting some PRs that partly make this work and to divide up your remaining plan. I knew this would not be a super easy PR to finish. Also happy to accept plenty of `# type: ignores` and we can try go back through them as things gets resolved - e.g. pytest 6 arrived.

If you'd like more real time chat we can do that too on IRC - irc.freenode.net #bandersnatch. We have a few active maintainers hang out in there very regularly now!
