### ISSUE TITLE
Abstract Storage and allow Any backend storage

### ISSUE THREAD

**Issue by LeoQuote** [pypa/bandersnatch#437]
We have a whole mirror for public use , it costs a lot of storage and bandwidth, so we decided to move it to s3 storage .

My current solution is to use bandersnatch sync pypi.org and then use s3cmd to sync all files to s3. But it has been tons of files , it really cusome time to do so(comparing each of files, transfer and check), I wonder if I can make use of bandersnatch , can I use bandersnatch to write files directly to s3. Or can I use the metadata in bandersnatch , like which package has been updated lately, so I can only sync those packages.

**Comment by LeoQuote** [comment]
[s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse) could be a solution for this , but it's not perfect , it requires root privellege to mount fs, which cannot achive easily inside container or k8s.

**Comment by cooperlees** [comment]
The fuse module could be a good comprimise, but, I am up for refactoring the code to allow for $cloud bucket storage to be supported for the backend file blobs.

What needs to be worked out is how to store and generate the simple html, for https://www.python.org/dev/peps/pep-0503/ support which pip etc. requires. The simple html would still need to be hosted in a way to allow it to be accessed via https, so it might need need to be on a POSIX file system and all the blobs live in a bucket.

Does s3 / other buckets have friendly API calls to give us listing of directories etc.? Generating this HTML could cause a lot of API calls to be made. This would need to be thought about, but we could be a lot smarter than the current walking of the POSIX file system here. For example, keep track of the changed packages and only regenerate them, and then ONLY generate the main `index.html` if a package is added or deleted since the last run. If possible, I'd also like to keep bandersnatch as stateless as possible.

**Comment by LeoQuote** [comment]
for aws s3, there is rather friendly api to get a list of directory, example as below:

```python
import boto3

s3 = boto3.resource('s3')
bucket = s3.Bucket('my-bucket')
for obj in bucket.objects.filter(
    Delimiter='/',
    EncodingType='url',
    Marker='string',
    MaxKeys=123,
    Prefix='simple',
    RequestPayer='requester'
):
    print(obj.key)
```

we can get all the directory key and then generate a `simple/index.html` 

I think a good way to do it is to summarize what file operations do we need during the whole process, we can see is there any equivalent method for those cloud storage .

**Comment by techalchemy** [comment]
So I've just gone through and taken a stab at implementing [swift](https://www.openstack.org/software/releases/train/components/swift) integration (the openstack object store) -- I haven't written any tests yet, but after reading through the code and evaluating the options the best fit I came up with was to abstract all the file operations into a `StoragePlugin` and subclass from there.

I went a bit further with swift to gain some performance, building out a custom `pathlib.PurePath` subclass with its own `accessor` helper class.  I will put up a WIP PR and we can discuss if that makes sense to everyone

**Comment by LeoQuote** [comment]
@techalchemy That's brilliant! Are you using [python-swiftclient](https://github.com/openstack/python-swiftclient) or some web request libs like requests or urllib ?

**Comment by cooperlees** [comment]
This all sounds great to me. My first goal was to probably do the I/o abstraction and make this base class. Then layer the respective object stores on top. Would love to see the PR and I’ll comment away on that.

My only other request is now that I did the work of moving everything to aiohttp, that we use that or an asyncio client library of choice. I’d also like, if we do add more deps for them to be optionally installed as most people won’t need a swiftclient etc.

**Comment by techalchemy** [comment]
> Are you using python-swiftclient

Yep, that's the one

> My first goal was to probably do the I/o abstraction and make this base class

That was the first step, I wound up tweaking this a bit but it should be ok to start with. This will likely need some adjustment so I'm willing to work with whatever you want to do. I'll make sure you have push access to the branch

> My only other request is now that I did the work of moving everything to aiohttp, that we use that or an asyncio client library of choice

This might complicate things a bit since most of the client libraries are not async-compatible (afaik) -- so it may mean implementing by hand.  The implementation I have is synchronous (and yeah, it's a bit slow)

>  if we do add more deps for them to be optionally installed as most people won’t need a swiftclient etc.

For sure, they would have to be optional
