### ISSUE TITLE
Proposal: A general API for PyPI mirroring tools

### ISSUE THREAD

**Issue by dralley** [pypa/bandersnatch#548]
Proposal
========

Bandersnatch is the top tool for mirroring PyPI. It's well tested in production, PEP-compliant, and generally respectful of PyPI's resources. It would be excellent if Bandersnatch could be refactored to provide a common library for all mirroring tools interacting with PyPI.

Benefits to Bandersnatch:

* More testing
* More eyes on the code
* More stakeholders willing to fix bugs and make improvements in Bandersnatch which will trickle down to their own projects

Benefits to the Python ecosystem:

* Easier to change Warehouse APIs (e.g. remove XML-RPC, add new JSON APIs) if Bandersnatch is the only consumer of those APIs (and other mirroring tools just use Bandersnatch)

What we need
============

I write this as a contributor to one of these other mirroring tools (although we do more "repo management" rather than just mirroring). Here is the functionality we would need from Bandersnatch (including things that might already be do-able):

* The ability to parse Bandersnatch config files and get the configuration data back in a form that we can save as settings in our database, and re-constitute later for use by the mirroring stage
* The ability to filter PyPI packages/releases using the filters Bandersnatch provides
* The following metadata about each package that passes through the filters:
    * filename
    * packagetype
    * name
    * version
    * metadata_version
    * summary
    * description
    * keywords
    * home_page
    * download_url
    * author
    * author_email
    * maintainer
    * maintainer_email
    * license
    * requires_python
    * project_url
    * platform
    * supported_platform
    * requires_dist
    * provides_dist
    * obsoletes_dist
    * requires_external
    * classifiers
* The download url to the actual file in the PyPI datastore

Current Problems
================

Problem: Separation of concerns - the communication with PyPI isn't very separated from internal Bandersnatch-specific behavior.

a) It looks like the primary entry point, Mirror.synchronize(), unavoidably tries to touch the filesystem in various ways that are needed by Bandersnatch but not for someone calling Bandersnatch as a library, such as:

* "todolist"
* "last_modified"
* "statusfile"

b) It doesn't seem that there is a way to ask Bandersnatch to abstain from downloading the package files (or JSON files? unclear on that one) and saving them to disk.

We need to handle downloading the package file ourselves, the only thing we need is the JSON metadata (as a dict or string) and the package download URL.

[deleted tangent about *why* we need it]

Solution
========

Separate the concerns a little bit better. I think the following suggestions would be the *minimum* necessary changes:

Split the "Mirror" class in half, create a new one which handles everything up to and including "determine which packages to sync", while the existing class handles the logic behind persisting it to disk, error handling, and cleaning up.

Inside the Package class, move the code which handles the metadata download from Package.sync() into a new method called request_metadata() or something, so that it can be called separately.

Remove the need for Package to hold a reference to Mirror - several changes needed here to the flow of errors.

**Comment by techalchemy** [comment]
> We need to handle downloading the package file ourselves, the only thing we need is the JSON metadata (as a dict or string) and the package download URL.

> [deleted tangent about why we need it]

I'm a bit curious about why you need to download them yourself, because I feel like bandersnatch is primarily a mirror  and if you are going to separate concerns, bandersnatch should remain a mirror and the rest of the functionality should be grouped and abstracted for its specific use case.

In my mind, the overall solution that I am imagining looks something like this:

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBW1BhY2thZ2UgTGlzdF0gLS0-fFhNTFJQQyBRdWVyeXwgQltQYWNrYWdlIFdvcmsgUXVldWVdXG4gICAgQiAtLT58RG93bmxvYWQgUGFja2FnZXN8IENbU3RvcmFnZSBCYWNrZW5kXVxuICAgIEIgLS0-fERvd25sb2FkIE1ldGFkYXRhfCBEW01ldGFkYXRhIFN0b3JlXVxuICAgIEMgLS0-fFBhY2thZ2UgTG9jYXRpb25zfCBEXG4gICAgRCAtLT4gRVtJbiBNZW1vcnkgQ2FjaGVdXG4gICAgRSAtLT4gRltEeW5hbWljIFdlYnNlcnZlciBlLmcuIEZsYXNrXVxuICAgIEYgLS0-IEdbV2Vic2VydmVyXSAtLT4gSVtMb2FkIEJhbGFuY2VyXVxuICAgIEYgLS0-IEhbV2Vic2VydmVyXSAtLT4gSltMb2FkIEJhbGFuY2VyXVxuICAgIEcgLS0-IEtbTG9hZCBCYWxhbmNlcl1cbiAgICBIIC0tPiBLXG4gICAgRyAtLT4gSlxuICAgIEggLS0-IEkiLCJtZXJtYWlkIjp7InRoZW1lIjoiZm9yZXN0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBW1BhY2thZ2UgTGlzdF0gLS0-fFhNTFJQQyBRdWVyeXwgQltQYWNrYWdlIFdvcmsgUXVldWVdXG4gICAgQiAtLT58RG93bmxvYWQgUGFja2FnZXN8IENbU3RvcmFnZSBCYWNrZW5kXVxuICAgIEIgLS0-fERvd25sb2FkIE1ldGFkYXRhfCBEW01ldGFkYXRhIFN0b3JlXVxuICAgIEMgLS0-fFBhY2thZ2UgTG9jYXRpb25zfCBEXG4gICAgRCAtLT4gRVtJbiBNZW1vcnkgQ2FjaGVdXG4gICAgRSAtLT4gRltEeW5hbWljIFdlYnNlcnZlciBlLmcuIEZsYXNrXVxuICAgIEYgLS0-IEdbV2Vic2VydmVyXSAtLT4gSVtMb2FkIEJhbGFuY2VyXVxuICAgIEYgLS0-IEhbV2Vic2VydmVyXSAtLT4gSltMb2FkIEJhbGFuY2VyXVxuICAgIEcgLS0-IEtbTG9hZCBCYWxhbmNlcl1cbiAgICBIIC0tPiBLXG4gICAgRyAtLT4gSlxuICAgIEggLS0-IEkiLCJtZXJtYWlkIjp7InRoZW1lIjoiZm9yZXN0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

Where the in memory cache, the storage backend, and the metadata store (i.e. the database) can be swapped out via a plugin system.

Currently the storage backend is getting abstracted a bit to allow for more generic implementations (like S3-based file storage).

Ideally, we could move away from so much filesystem interaction. Using a queue like redis or I mean, aren't all the kids using kafka for everything these days? Surely you should be deploying kafka somewhere in there just to fit in. (That's sarcasm)

If you *only* care about downloading metadata, depending on what specific information you need, I have some extra tooling built for this already over at https://requirementslib.readthedocs.io/en/master/requirementslib.models.metadata.html#requirementslib.models.metadata.get_package (`get_package(<pkgname>)` and `get_package_version(<pkgname>, <pkgversion>)`) -- but these are designed for the use case of retrieving dependency metadata and written with python 2 compatibility so they are not `asyncio` capable.

Anyhow, I'd argue you could make completely different libraries here, but I'm on board with splitting up the mirror functionality to start off with since I agree that metadata and actual data are totally independent. Like you, I need to put the metadata into a database (and would love to have that logic shared as well, but suspect your approach is implemented already). Unlike you I do still need the files.

**Comment by dralley** [comment]
>If you only care about downloading metadata,

Well, it's not just that we want the metadata, it's that we want as little metadata as we can get away with (the XML-RPC APIs are helpful here) and we want to support most of the same filtering features that Bandersnatch already supports, so sharing an implementation with Bandersnatch would be really useful.

>  I'm a bit curious about why you need to download them yourself

So this is the bit I deleted earlier because it's not really that relevant to the issue.  There's many reasons but the primary one is that one of the primary features of Pulp is "lazy sync", which is basically an on-demand caching behavior.  Basically Pulp will ingest all of the metadata and create the desired mirror without actually downloading any of the packages until a client asks Pulp for them.  It's a trade off of a small amount of robustness in exchange for saving a huge amount of disk space and bandwidth on packages that will never actually be used.

But because we support this feature, the architecture makes the assumption that Pulp is performing the actual package download itself (whether it's doing so immediately during the initial mirror, or on-demand when requested).

**Comment by cooperlees** [comment]
What else is the plan here? Can we maybe spell out the remaining plans so there is an endpoint for this issue if possible?

**Comment by pombredanne** [comment]
Let me thrown in my requirements: I have a few  use cases where we maintain mostly a mirror of metadata and selectively will download actual files only if needed. There I want to run a daily or hourly process to update that system of mine and I was about to start extracting the bits I needed from bandersnatch. Enhancing the code here instead would be a much better option. I feel my use is not much different from Pulp so I am game to help. As @dralley pointed out, it would be much better for me to call bandersnatch as a library rather than reimplementing or fork a metadata-focused subset that would be tied to the legacy xmlrpc API.

**Comment by dralley** [comment]
@pombredanne Here's what we're working on at the moment in our PR

https://github.com/pypa/bandersnatch/blob/37cabc7ab554beb016bf98ff4778e9dbb071f769/src/bandersnatch/mirror.py#L33-L178

As an API user, the methods that a subclasser would need to implement are:

* ```determine_packages_to_sync()  # init the structures that define the packages to be synced```
* ```process_package(package)  # called for each Package object (do things like saving the json and downloading packages -- or not)``` 
* ```finalize_sync()  # called once at the end of the sync (do things like write index file -- or not)```

Do you think that would be sufficient for your purposes?  Of course technically anything can be overridden but it would be great if we can define a clear interface that allows all the behavior to be customized without doing such things.

We would definitely love your feedback.  There is probably still plenty of things that could be improved, especially around  ```determine_packages_to_sync()```.

**Comment by dralley** [comment]
Link to the PR https://github.com/pypa/bandersnatch/pull/591

**Comment by pombredanne** [comment]
@dralley re: 
> Here's what we're working on at the moment in our PR

Thank you ++... let me play with that

**Comment by cooperlees** [comment]
Can we call this done and release? Please reopen if not, and please open those cleanup issues you were talking about :D
