### ISSUE TITLE
integration with safety-db

### ISSUE THREAD

**Issue by gpcimino** [pypa/bandersnatch#55]
Hi all,

I am providing PyPI mirror to local users using bandersnatch. It works great!
However if some package is insecure I am bringing home some potentially risky stuff.

I am wondering if implementing some bandersnatch filtering based on [Python insecure database](https://github.com/pyupio/safety-db) would be possible.

Do this make sense? 
Does something like that exists already?
Are you aware of possible integration with other security db source (e.g. CVE)?

Thanks
GP

**Comment by cooperlees** [comment]
Hi,

This does seem sane to me, but it should be optional as I am sure there would be someone who wants it off.

You could use safety DB to generate a blacklist file compatible with bandersnatch and achieve your goal of blocking known bad packages today:
https://bandersnatch.readthedocs.io/en/latest/filtering_configuration.html#blacklist-filtering-settings
- You would have to use trunk as 3.0 is still no released. I need to do that.

I'd also accept a config controlled feature/plugin that checks the DB for every new package + version downloaded. Please try and make it be an async call or be in the same threadpool that we use today to download packages (which is controller by workers in the config file).

**Comment by gpcimino** [comment]
I agree that this feature must be optional.

Generate a blacklist compatible file is for sure a quick mitigation. I am not sure if blacklist just blocks download of new packages or also removes packages from the local file system (honestly I haven't dig into the source code yet ;-) ). Think to 0-day vulnerability: at download time a vulnerability might be still unknown and once it become available on Python Insecure Database the bad package is already in house.
To solve this problem I need to be able to delete/quarantine the local files once deemed vulnerable.

Do this make sense?
Can a feature/plugin help better?

**Comment by dwighthubbard** [comment]
The blacklisting functionality is plugin based so I would think it would be cleanest to implement this as another blacklist plugin. 

I would imagine it would be a matter of creating a new plugin derived from the existing blacklist plugin and extending the blacklist parsing code to read from the Python insecure database.

**Comment by dwighthubbard** [comment]
I'll take a stab at getting a safety blacklist plugin implemented at the Pycon sprints.

**Comment by dwighthubbard** [comment]
i started looking at this yesterday and found the safety-db packages currently have an issue where they don't actually contain the database files.  I have opened #pyupio/safety-db#2277 to hopefully fix the packaging issue. 

If the packaging issue isn't fixed in time we'll have to write the plugin to get the safety-db from the git repo instead of the package (which would probably be good to support as an option anyways).

**Comment by cooperlees** [comment]
Yeah, pulling it in will leave the DB stuck at a version pull during our releases of bandersnatch. I don't really want to have to do a weekly releases of bandersnatch just to keep this db up to date.

Lets whiteboard this tomorrow, but I feel a check and fetch, if there is a newer version, (with a config option) at startup makes sense to me.

**Comment by dwighthubbard** [comment]
Ok, the plugin versioning functionality is now in bandersnatch to support the external optional plugin  that works with multiple bandersnatch releases.

The safety_db filterin is provided by the [bandersnatch_safety_db](https://pypi.org/project/bandersnatch-safety-db/) package.

Currently the plugin fetches safety_db from github because the safety-db package is still broken.
