### ISSUE TITLE
delete-packages not working

### ISSUE THREAD

**Issue by SuperCloserZita** [pypa/bandersnatch#645]
Hi：

Version：bandersnatch 3.6.0

`master = https://pypi.python.org`
`delete-packages = true`

I made delete-packages option is true in my bandersnatch.conf,But the option seems like not working.

Example：
The package **request**  deleted from the pypi.org on 31,July, But it still stored in my pip server and I didn't find any deleted record in the log。

Look forward to your favourable reply,Thanks.

**Comment by cooperlees** [comment]
Hi,

3.6.0 is a very old version. Delete was removed as it was (as you’ve found) broken due to PyPI backend changes. These changes made it very hard to delete during a sync.

I would suggest updating to latest bandersnatch and using the “verify” option to cleanup and delete packages.

(You may have to use master, as we need to get a release out with other big fixes)

**Comment by cooperlees** [comment]
4.2.0 is out and should have all fixes needed here.

**Comment by SuperCloserZita** [comment]
> 4.2.0 is out and should have all fixes needed here.

Thanks Lees, I will do some tests.

**Comment by cooperlees** [comment]
No problems. Please reopen if issue still occurs. Please give examples + your config and version. Thanks!
