### ISSUE TITLE
Pinning Deps reduces package Flexibility

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#81]
If you don't use a virtualenv and have large monorepos pinning deps hard can cause a lot of uneeded pain. For example at the moment, bandersnatch has everything set via `==`, in a shared repos if someone moves requests or any bandersnatch dependency forward bandersnatch will complain and fail to execute.

## Suggestions and would love some feedback:
- Change requirements to >= to at least allow moving forward and ONLY pin if a newer version causes issues - *Could introduce more travis runs when new versions come out etc.*
- Find the lowest version we work with and `>=` it in requirements.txt
- Go back to un-versioned setup.py install_requires and leave it up to the deployment to respect requirements.txt or not

**Comment by dwighthubbard** [comment]
I think the unversioned setup.py install_requires would be correct.  Pinning versions in setup.py is a [bad pattern](https://packaging.python.org/discussions/install-requires-vs-requirements/) since the setup.py should be used to specify what a project minimally needs to run correctly.

If we were going to put any versioning of dependencies in the setup.py I would think pinning the minimum versions and possibly capping the major versions for some packages would be reasonable.

The requirements.txt and test-requirements.txt files should have pinned concrete dependencies to create a known working environment.

So I would be all for moving the pinned versioning out of setup.py and putting abstract deps in say setup.cfg.

**Comment by yeraydiazdiaz** [comment]
I agree with @dwighthubbard, depending on how cutting edge we want to be we could consider a [`pyproject.toml`](https://www.python.org/dev/peps/pep-0518/) and/or [Poetry](https://github.com/sdispater/poetry)

**Comment by cooperlees** [comment]
Agree - Reversing my setup.py change. Thanks all!

**Comment by cooperlees** [comment]
Have reverted to non versioned setup.py, but it seems most people would like atleast >= in the setup.py for minimum deps. I'll work on a PR for that.

I also want to setup some autoupdate setup, like Warehouse. This will be low risk once we have a CI Integration test that is being tracked in #78
