### ISSUE TITLE
Support downloading files from alternative PyPI mirrors

### ISSUE THREAD

**Issue by happyaron** [pypa/bandersnatch#869]
bandersnatch currently downloads all files from the master PyPI archive, honoring the "url" in json respose which by default points to files.pythonhosted.org. Although creating a local master is theoretically possible, it is not practical when most people is mirroring the content with bandersnatch.

This feature is useful to sync most of the files from an existing, nearby mirror, for example when setting up a new server sitting next to an existing one for the purpose of load sharing. 

The design could be quite straightforward:
1. create a new configuration item which is disabled by default
2. if configured, try to download files from the specified alternative mirror first, and fallback to the "url" in json response from PyPI master
3. data integrity is checked by the sha256sum which bandersnatch always verifies for newly downloaded content

**Comment by cooperlees** [comment]
Hi, good suggestion. I would accept this fallback logic PR.

Something like:
preferred_mirror = https://mirror.com/simple

then add this to the Master class and HTTPS get methods.

Like you said, all XMLRPC will still have to hit PyPI.org but static fetchers could try the mirror first, catch any exception and fallback to the PyPI CDN.

**Comment by mbacicc** [comment]
Can this option be also useful to use bandersnatch packages to serve local network (by using nginx or banderx) joining packages from pypi and local packages?

I'll explain better, we are using pypiserver for distributing inside our network some django packages which integrates html themes that we bought from themeforest, thus we can't publish these packages on pypi as per themes license.

When we run tests on CI we have to add both bandersnatch http/s server and pypiserver addresses as pip sources in order to serve both mirrored pypi packages and our internal packages. It would be cool to have both merged in some way.

If bandersnatch main mirror was local pypiserver and the "second" was pypi, I imagine that this scenario could be working. Am I right?

**Comment by happyaron** [comment]
@mbacicc I don't think this option is for merging two repositories... bandersnatch is configured only to get index from one PyPI instance (i.e. the main index API), and it could try to download the actual binaries from an alternative server, so it has no knowledge of packages provided by another API server (in your case the pypiserver instance).
