### ISSUE TITLE
How do I set multiple mirrors in bandersnatch?

### ISSUE THREAD

**Issue by GreatBahram** [pypa/bandersnatch#89]
Hello fellas
Is this possible to have multiple masters in bandersnatch configuration?
And would it be possible to use bandersnatch in order to clone devpi package index as well?

Thanks

**Comment by cooperlees** [comment]
- Is this possible to have multiple masters in bandersnatch configuration?
No - bandersnatch is super PyPI specific due to the XML RPC + JSON APIs

- And would it be possible to use bandersnatch in order to clone devpi package index as well?
No. Since this is internal, just use rsync possibly. (I've also never used devpi - So don't know their layout etc.)

**Comment by GreatBahram** [comment]
Thanks @cooperlees, my goal was to clone multiple Python package index(pypi and internal repositories). I just wanted to know can I count on `bandersnatch` or not.
You have been a great help here
