### ISSUE TITLE
Add Discord chat to Documentation

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#924]
- Mention we now sit in Discord in docs

**Comment by default-303** [comment]
hey, can i have this issue?

**Comment by mohitbalwani** [comment]
Hey! I would like to work on this issue!

**Comment by ichard26** [comment]
Hi y'all,

So for context, we just switched our real-time communication platform from Freenode IRC to Discord. We moved to the PyPA server on Discord and we have our own little text channel for bandersnatch specifically. 

So what has to be done for this issue is to replace our mention of IRC for Discord (in particular the PyPA server and the #bandersnatch text channel) here: https://github.com/pypa/bandersnatch#contact

**Comment by mohitbalwani** [comment]
Am I supposed to replace the IRC line of contact section with Discord
details?

**Comment by ichard26** [comment]
Yes.
